/*
  Warnings:

  - You are about to drop the column `bid` on the `Blog` table. All the data in the column will be lost.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_Blog" (
    "title" STRING NOT NULL,
    "shortContent" STRING NOT NULL,
    "content" STRING NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isPublic" BOOL NOT NULL,
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,

    CONSTRAINT "Blog_pkey" PRIMARY KEY ("id")
);
DROP INDEX "Blog_title_key";
INSERT INTO "_prisma_new_Blog" ("content","date","email","isPublic","shortContent","title") SELECT "content","date","email","isPublic","shortContent","title" FROM "Blog";
DROP TABLE "Blog" CASCADE;
ALTER TABLE "_prisma_new_Blog" RENAME TO "Blog";
CREATE UNIQUE INDEX "Blog_title_key" ON "Blog"("title");
